name: Go
on:
  push:
    branches:
      - "master"
      - "chore/test2"
  pull_request:
    branches:
      - "master"
jobs:
  lint-go:
    name: Lint Go code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.30
          args: --timeout 5m
  codegen:
    name: Verify Codegen
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.17.6
      # k8s codegen generates files into GOPATH location instead of the GitHub git checkout location
      # This symlink is necessary to ensure that `git diff` detects changes
      - name: Create symlink in GOPATH
        run: |
          mkdir -p ~/go/src/github.com/argoproj
          ln -s $(pwd) ~/go/src/github.com/argoproj/argo-rollouts
      - uses: actions/cache@v2
        with:
          path: /home/runner/.cache/go-build
          key: GOCACHE-${{ hashFiles('**/go.mod') }}
      - uses: actions/cache@v2
        with:
          path: /home/runner/go/pkg/mod
          key: GOMODCACHE-${{ hashFiles('**/go.mod') }}
      - uses: actions/cache@v2
        with:
          path: /home/runner/go/bin
          key: go-bin-v1-${{ hashFiles('**/go.mod') }}
      - name: Install protoc
        run: |
          make install-toolchain
      - name: Add ~/go/bin to PATH
        run: |
          echo "/home/runner/go/bin" >> $GITHUB_PATH
      - name: Add /usr/local/bin to PATH
        run: |
          echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Run codegen
        run: |
          make go-mod-vendor
          make codegen
          make manifests
          make docs

      - name: Ensure nothing changed
        run: git diff --exit-code
